# data analysis and visualization-Harshit vashishth

In [2]:
import numpy as np

In [4]:
#list convert in array
nums = [1,2,3]

In [5]:
nums = np.array(nums)

In [6]:
nums

array([1, 2, 3])

In [24]:
#2D matrix
nums = [[1,2,3],[4,5,6]]

In [25]:
nums=np.array(nums)

In [32]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
nums.ndim


2

In [34]:
nums.shape

(2, 3)

In [21]:
#3D matrix
nums = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
nums = np.array(nums)
nums

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
nums.ndim

3

In [28]:
nums.shape

(2, 3)

In [36]:
#numpy store single data type
nums.dtype

dtype('int32')

In [41]:
#if we using single float value then all the datatype will be float
a=[1,2,3.0]
a=np.array(a)
a

array([1., 2., 3.])

In [42]:
a.dtype

dtype('float64')

In [49]:
#if we using single str value the all the datatype will be string.
b=[1,2,'3']
b=np.array(b)
b

array(['1', '2', '3'], dtype='<U11')

In [50]:
b.dtype

dtype('<U11')

In [57]:
#boolean value store
c=[1,2,'3',True]
c=np.array(c)
c

array(['1', '2', '3', 'True'], dtype='<U11')

In [58]:
c.dtype

dtype('<U11')

# create array using numpy function
<h2>zeros,ones,eyes,diag,randint,rand,randn</h2>


In [60]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [61]:
#2D matrix zero
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [66]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
#eye= eye have 2d metrics with the digonal 1.
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [70]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [83]:
#to find digonal value
np.diag(arr)

array([1, 2, 3, 4])

In [72]:
# random number genrate
rand_arr = np.random.randint(1,15,4) #genrate the number between 1 to 15.in these number 1 may be include but 15 exclude.
rand_arr

array([ 8, 10,  6, 13])

In [74]:
# rand function
rand_arr = np.random.rand(4)   #between 0 to 1 we get 4 value randomily.
rand_arr

array([0.34650791, 0.79947959, 0.09902729, 0.67784177])

In [75]:
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.59556701, 0.25017023, 0.9127857 ],
       [0.95904339, 0.25813144, 0.36725393]])

In [81]:
#randn function
rand_arr = np.random.randn(4)   #we get these number in standard normal distribution.(positive and neg. number)
rand_arr

array([ 0.09788071,  0.8950616 , -0.10222822,  1.29650654])

In [85]:
rand_arr = np.random.randn(100)
np.mean(rand_arr)   #mean mens avg...mean approx to zero

0.009204058113285762

# Reshaping of Data

In [108]:
import numpy as np
arr=np.random.randint(1,100,20)
arr


array([45,  1, 23, 89, 57, 49, 74, 45, 62, 69, 37, 20, 83, 99,  1, 39, 45,
       80, 21, 18])

In [109]:
arr.ndim

1

In [110]:
arr.shape

(20,)

In [111]:
#reshape mtlb 1D ko 2D me ya 3D me convert krna ya 2D ko 1D me
arr=arr.reshape(2,10)     #2,10=2*10=20
arr

array([[45,  1, 23, 89, 57, 49, 74, 45, 62, 69],
       [37, 20, 83, 99,  1, 39, 45, 80, 21, 18]])

In [112]:
arr.shape

(2, 10)

In [113]:
arr.ndim

2

In [97]:
arr=arr.reshape(20)

In [98]:
arr.ndim

1

In [116]:
arr=np.random.randint(1,20,18)
arr=arr.reshape(2,9)
arr

array([[ 3, 14,  7,  9, 18,  4,  8, 15, 14],
       [17,  7,  7,  6, 16, 19, 14, 16,  9]])

In [117]:
arr=arr.reshape(2,3,3)
arr

array([[[ 3, 14,  7],
        [ 9, 18,  4],
        [ 8, 15, 14]],

       [[17,  7,  7],
        [ 6, 16, 19],
        [14, 16,  9]]])

# what is reshape()

In [118]:
arr=np.arange(1,11)

In [119]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [122]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [123]:
arr.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [126]:
arr= np.arange(1,111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [129]:
arr.size

110

In [128]:
arr.reshape(5,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [130]:
arr.reshape(-1,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

# numpy:seed function-genrate same random number

In [3]:
import numpy as np
arr=np.random.randint(1,101,10)
arr

array([ 2, 23, 39, 73, 90, 74, 44, 24, 22, 78])

In [4]:
np.random.seed(12)   
arr=np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [165]:
arr.size

10

# numpy:indexing and slicing of 1-D array

In [166]:
arr=np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [167]:
# indexing mtlab position-position 0 se start hoti hai array me
arr[1]

10

In [168]:
arr[-1]

25

In [171]:
arr[-4]

10

In [173]:
# slicing
arr[2:5]

array([15, 20, 25])

In [174]:
arr[1:-1]

array([10, 15, 20])

In [177]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [178]:
arr[:-2]

array([ 5, 10, 15])

In [179]:
arr[1:]

array([10, 15, 20, 25])

In [180]:
arr[-3:]

array([15, 20, 25])

In [181]:
# step argument
arr[1:4:2]

array([10, 20])

In [184]:
arr[0::2]

array([ 5, 15, 25])

In [185]:
# array reverse
arr[::-1]

array([25, 20, 15, 10,  5])

# numpy:indexing and slicing of 2-D array

In [187]:
# create 2D array
import numpy as np
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [188]:
# indexing using double bracket notation
# if we want to access 10-first find the index position,then value postion
matrix[0][1]

10

In [189]:
matrix[1][-1]

30

In [195]:
# indexing using single bracket notation
# if we want to access 10
matrix[0,1]

10

In [196]:
matrix[2,2]

45

In [197]:
# slicing using single bracket notation
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [198]:
# if we want number 5,10,20,25 then
matrix[:2,:2]    #  :2 mens row 0 and col 1 and again :2 mens row 1 and 2 col

array([[ 5, 10],
       [20, 25]])

In [199]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [205]:
np.random.seed(123)
matrix2=np.random.randint(1,100,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [ ]:
#[[87, 98, 97],
#[33, 47, 97],
#[79, 37, 97]]  if we want to get this array

In [206]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

# Numpy :view VS copy

In [212]:
import numpy as np
arr= np.array([5,10,15,20,25])

In [214]:
arr2=arr[2:5]

In [215]:
arr2

array([15, 20, 25])

In [216]:
# now we change all the value of arr2
arr2[:]=0

In [217]:
arr2

array([0, 0, 0])

In [218]:
arr   #arr also changed.
    #becaue in numpy --- arr2=arr[2:5]--arr2 ne value only view ki hai copy nhi ki.mtlb isne memory me new location nhi li.

array([ 5, 10,  0,  0,  0])

In [219]:
# if we want to copy array
arr= np.array([5,10,15,20,25])

In [221]:
arr2=arr[2:5].copy()     #copy() use this function

In [222]:
arr2

array([15, 20, 25])

In [223]:
arr2[:]=0

In [224]:
arr2

array([0, 0, 0])

In [225]:
arr

array([ 5, 10, 15, 20, 25])

# Numpy : conditional selection

In [19]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr>5           #this condition applies on all the values.

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
mask=arr>5

In [22]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [23]:
# or
arr[arr<4]

array([1, 2, 3])

In [24]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [25]:
arr[arr==5]

array([5])

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#we can use 'conditional' in  broadcasting 
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# Numpy : operation with 'scaler'

In [243]:
arr= np.array([1,2,3,4])


In [244]:
arr*2

array([2, 4, 6, 8])

In [245]:
arr

array([1, 2, 3, 4])

In [246]:
arr+5

array([6, 7, 8, 9])

In [247]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [248]:
arr**3

array([ 1,  8, 27, 64], dtype=int32)

In [249]:
# these operaion will be aplly on 2D or 3D 
arr= np.array([1,2,3,4]).reshape(2,2)


In [250]:
arr

array([[1, 2],
       [3, 4]])

In [251]:
arr**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [252]:
arr+5

array([[6, 7],
       [8, 9]])

In [30]:
# In numpy zero devision error
1/0

ZeroDivisionError: division by zero

In [254]:
# but in array (arr/0) we receive warning or  infinty.
arr/0 

C:\Users\Abhishek Sharma\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, inf],
       [inf, inf]])

# Operation on two or more array

In [255]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [256]:
arr1+arr2

array([ 6,  8, 10, 12])

In [257]:
arr1*arr2

array([ 5, 12, 21, 32])

In [259]:
# shape will be same otherwise we get an error
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9])
arr1+arr2


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [260]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [261]:
arr1**arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [263]:
arr1*arr1

array([ 1,  4,  9, 16])

In [265]:
arr2/arr2

array([1., 1., 1., 1.])

In [266]:
arr3 = np.array([9,10,11,12])

In [267]:
arr1/arr1*arr3   

array([ 9., 10., 11., 12.])

In [ ]:
# matrix

In [273]:
np.random.seed(123)
mat1 = np.random.randint(1,12,9).reshape(3,3)
mat2 = np.random.randint(5,15,9).reshape(3,3)

In [274]:
mat1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [275]:
mat2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [276]:
# it is necessary that the shape of metrix will be same.
mat1+mat2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [277]:
mat1*mat2  

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [278]:
mat1.dot(mat2)   # this multipication use in linear algebra ---use dot() function(row*col)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

# some more useful numpy function

In [292]:
arr = np.array([2,80,1,97,5])

In [293]:
np.min(arr)

1

In [294]:
np.max(arr)

97

In [295]:
# if we want to know the postion of minimum number---use argmin() function
np.argmin(arr)

2

In [296]:
# if we want to know the postion of maximum number--use argmax() function
np.argmax(arr)

3

In [297]:
# find squreroot of every number
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [298]:
arr

array([ 2, 80,  1, 97,  5])

In [302]:
np.exp(arr)   #exponential is a oyal number.the value of exp is --2.71828 

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [304]:
2.71828**2

7.3890461584

In [305]:
2.71828**80

5.5403242392390125e+34

In [306]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [307]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [322]:
np.linspace(1,15,50) #if we want to get 50 number between 1 to 15 in the linespace 1 and 15 included.

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [330]:
np.linspace(1,50,5)     

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [ ]:
# how to change array in boolean array

In [332]:
arr

array([ 2, 80,  1, 97,  5])

In [337]:
arr2 = np.array([1,2,3,0],dtype='bool')
arr2

array([ True,  True,  True, False])

In [338]:
arr3 = np.array([1,0,1,1],dtype='bool')
arr3

array([ True, False,  True,  True])

In [339]:
for i in arr2:
    print(i)

True
True
True
False


# Numpy Axis:

In [1]:
import numpy as np

In [4]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [5]:
matrix.sum()

39

In [6]:
# or 
np.sum(matrix)

39

In [7]:
np.min(matrix)

1

In [8]:
np.max(matrix)

10

In [9]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [10]:
# if we want to find minimum number in rows
np.min(matrix,axis=1)

array([3, 2, 1])

In [11]:
# if we want to find minimum number in colms.
np.min(matrix,axis=0)

array([2, 2, 1])

In [12]:
np.sum(matrix,axis=1)

array([13, 16, 10])

In [13]:
np.sum(matrix,axis=0)

array([12,  9, 18])

In [14]:
# cumulative sum
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [15]:
np.cumsum(matrix,axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [16]:
np.cumsum(matrix,axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [17]:
np.product(matrix,axis=1)

array([63, 80, 14])

In [47]:
# or
np.prod(matrix,axis=0)

array([42, 24, 70])

# Numpy : shuffle and unique

In [42]:
np.random.seed(123)
arr=np.random.randint(1,15,15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [43]:
np.random.shuffle(arr)

In [44]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [45]:
# if we want to find unique number on array
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [46]:
np.unique(arr).size

10

In [47]:
np.unique(arr,return_index=True,return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

# Numpy : Horizontal and vertical stacking

In [27]:
np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)

In [28]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [29]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [31]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [32]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [33]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [35]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [36]:
# vertical me 2D matrix me aajyega
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy Array Vs Python Lists

In [ ]:
# numpy array is  faster as compair to list

In [48]:
%timeit 2+3

10.4 ns ± 0.375 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [38]:
%timeit [i**2 for i in range(1,4)]

1.64 µs ± 1.42 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [39]:
I = []
for i in range(1,4):
    I.append(i**2)
print(I)

[1, 4, 9]


In [50]:
%%timeit
I = []
for i in range(1,4):
        I.append(i**2)



1.89 µs ± 55.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
import numpy as np

In [52]:
%timeit np.arange(1,4)**2

2.6 µs ± 47 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# list and numpy runtime

In [53]:
%timeit [i**2 for i in range(1,11)]

5.13 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
%timeit np.arange(1,11)**2

2.6 µs ± 45.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [55]:
%timeit [i**2 for i in range(1,10000)]

5.18 ms ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [56]:
%timeit np.arange(1,10000)**2

18.6 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
